# TCL File Generated by Component Editor 12.1sp1
# Sat Feb 27 18:10:24 MST 2016
# DO NOT MODIFY


# 
# USB_Component "USB_Component" v1.0
# Eric Smith 2016.02.27.18:10:24
# USB Controller Communication
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module USB_Component
# 
set_module_property DESCRIPTION "USB Controller Communication"
set_module_property NAME USB_Component
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Communication
set_module_property AUTHOR "Eric Smith"
set_module_property DISPLAY_NAME USB_Component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL usb
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file usb_component.vhd VHDL PATH USB/usb_component.vhd
add_fileset_file DE2_CONSTANTS.vhd VHDL PATH USB/DE2_CONSTANTS.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL usb
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file usb_component.vhd VHDL PATH USB/usb_component.vhd
add_fileset_file DE2_CONSTANTS.vhd VHDL PATH USB/DE2_CONSTANTS.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point irq_dc
# 
add_interface irq_dc interrupt end
set_interface_property irq_dc associatedAddressablePoint DC
set_interface_property irq_dc associatedClock clock
set_interface_property irq_dc associatedReset reset_n
set_interface_property irq_dc ENABLED true

add_interface_port irq_dc avs_dc_irq irq Output 1


# 
# connection point irq_hc
# 
add_interface irq_hc interrupt end
set_interface_property irq_hc associatedAddressablePoint HC
set_interface_property irq_hc associatedClock clock
set_interface_property irq_hc associatedReset reset_n
set_interface_property irq_hc ENABLED true

add_interface_port irq_hc avs_hc_irq irq Output 1


# 
# connection point Conduit
# 
add_interface Conduit conduit end
set_interface_property Conduit associatedClock clock
set_interface_property Conduit associatedReset reset_n
set_interface_property Conduit ENABLED true

add_interface_port Conduit USB_ADDR export Output 2
add_interface_port Conduit USB_WR_N export Output 1
add_interface_port Conduit USB_RD_N export Output 1
add_interface_port Conduit USB_RST_N export Output 1
add_interface_port Conduit USB_CS_N export Output 1
add_interface_port Conduit USB_INT0 export Input 1
add_interface_port Conduit USB_INT1 export Input 1
add_interface_port Conduit USB_DATA export Bidir 16


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true

add_interface_port reset_n reset_n reset_n Input 1


# 
# connection point DC
# 
add_interface DC avalon end
set_interface_property DC addressUnits WORDS
set_interface_property DC associatedClock clock
set_interface_property DC associatedReset reset_n
set_interface_property DC bitsPerSymbol 8
set_interface_property DC burstOnBurstBoundariesOnly false
set_interface_property DC burstcountUnits WORDS
set_interface_property DC explicitAddressSpan 0
set_interface_property DC holdTime 4
set_interface_property DC linewrapBursts false
set_interface_property DC maximumPendingReadTransactions 0
set_interface_property DC readLatency 0
set_interface_property DC readWaitStates 25
set_interface_property DC readWaitTime 25
set_interface_property DC setupTime 0
set_interface_property DC timingUnits Nanoseconds
set_interface_property DC writeWaitStates 25
set_interface_property DC writeWaitTime 25
set_interface_property DC ENABLED true

add_interface_port DC avs_dc_address address Input 1
add_interface_port DC avs_dc_writedata writedata Input 16
add_interface_port DC avs_dc_write_n write_n Input 1
add_interface_port DC avs_dc_read_n read_n Input 1
add_interface_port DC avs_dc_readdata readdata Output 16
add_interface_port DC avs_dc_CS_n chipselect_n Input 1
set_interface_assignment DC embeddedsw.configuration.isFlash 0
set_interface_assignment DC embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment DC embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment DC embeddedsw.configuration.isPrintableDevice 0


# 
# connection point HC
# 
add_interface HC avalon end
set_interface_property HC addressUnits WORDS
set_interface_property HC associatedClock clock
set_interface_property HC associatedReset reset_n
set_interface_property HC bitsPerSymbol 8
set_interface_property HC burstOnBurstBoundariesOnly false
set_interface_property HC burstcountUnits WORDS
set_interface_property HC explicitAddressSpan 0
set_interface_property HC holdTime 0
set_interface_property HC linewrapBursts false
set_interface_property HC maximumPendingReadTransactions 0
set_interface_property HC readLatency 0
set_interface_property HC readWaitTime 1
set_interface_property HC setupTime 0
set_interface_property HC timingUnits Cycles
set_interface_property HC writeWaitTime 0
set_interface_property HC ENABLED true

add_interface_port HC avs_hc_address address Input 1
add_interface_port HC avs_hc_writedata writedata Input 16
add_interface_port HC avs_hc_write_n write_n Input 1
add_interface_port HC avs_hc_read_n read_n Input 1
add_interface_port HC avs_hc_readdata readdata Output 16
add_interface_port HC avs_hc_CS_n chipselect_n Input 1
set_interface_assignment HC embeddedsw.configuration.isFlash 0
set_interface_assignment HC embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment HC embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment HC embeddedsw.configuration.isPrintableDevice 0

